# Continuous integration config for travis-ci.org
language: node_js
node_js:
  - node  # Latest version

before_script:
  - npm install -g grunt bower
  - bower install

script: grunt   # Build and test

# Deploy using awscli to enable pruning of removed files
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://globaltschema.se --region=eu-central-1 --delete
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    # AWS secret key
    - secure: "F2d/D7cuowdCkUIhxq6nAoDDoapAw27o4Sl+cKir/KEtVOkDW7Hd670nyiaj1DPrB8jFneyYP0pxgX6WFRcwvc109J537Y0mI20NqFLr3jfTan8smJlz1YwalUSg3XYiRW0Iqv2Rt9cqXefvJ70KCqhdVgQdpA6u9z6I2c/b6uKLSrlsw508OLkp2jTG3rYdmps7jB0HQoFE7hJBrTCQ37w+hUbSgxe/mU/k9rLTQvu1yks/QvuJwjIHrv5dOmQSynbfyV1CnJ6Mxr/vOuR1AQd/hFiPAEFm4gkAxYY5uokHtqq/8rNquc3rzmyNZ/rdjuhsDvG2qdS/WJ/xnbI+Hme51TTk+4Gl394Zo+5UaaLUh6KPmK34S5UTzbxMFewUT2elihCo6qSTg73VRKF6Qc37K0KKbAZLAn1WeQ3qKcYJM58UlXqyMJoVD3WWyLdnByViYVl3FixnhsM3/ppTcMbqPL7WG2HnqCUg8+f+RIjTMLWKHNXTAmhPNDJGmahTCTcOE5CjhTa5pkkK7OOsb52u909/gxBFfXurCzorQx4yERK3JL4DR0wq2IzZGWZzkkyRkWZ6j+UOBN59ViJjSdUZavPx+4oMshQoEb51wkoh2+atplxj4O+o9AcZoXWogcgMeQHqMl39TX6/pn2zYuKHc/lQbMabop8K6TiNKyY="
    - AWS_ACCESS_KEY_ID=AKIAJ3QTQE6FXPGKHJYA